# 2026-06-25 05:21:01.847592
\.aaa$ whois.nic.aaa
\.accountant$ whois.nic.accountant
\.accountants$ whois-to-rdap.zerogon.consulting
\.ads$ whois-to-rdap.zerogon.consulting
\.aero$ whois.aero
\.aetna$ whois-to-rdap.zerogon.consulting
\.af$ whois.nic.af
\.agakhan$ whois.nic.agakhan
\.akdn$ whois.nic.akdn
\.analytics$ whois-to-rdap.zerogon.consulting
\.app$ whois-to-rdap.zerogon.consulting
\.apple$ whois-to-rdap.zerogon.consulting
\.asda$ whois.nic.asda
\.auto$ whois.nic.auto
\.band$ whois-to-rdap.zerogon.consulting
\.be$ whois.dns.be
\.bible$ whois.nic.bible
\.bid$ whois.nic.bid
\.biz$ whois.nic.biz
\.brother$ whois.nic.brother
\.buzz$ whois.nic.buzz
\.by$ whois.cctld.by
\.caravan$ whois-to-rdap.zerogon.consulting
\.case$ whois.nic.case
\.casino$ whois-to-rdap.zerogon.consulting
\.citi$ whois-to-rdap.zerogon.consulting
\.club$ whois.nic.club
\.cn$ whois.cnnic.cn
\.coop$ whois.nic.coop
\.coupons$ whois-to-rdap.zerogon.consulting
\.crs$ whois.nic.crs
\.cruises$ whois-to-rdap.zerogon.consulting
\.deal$ whois-to-rdap.zerogon.consulting
\.dental$ whois-to-rdap.zerogon.consulting
\.do$ whois.nic.do
\.epson$ whois.nic.epson
\.furniture$ whois-to-rdap.zerogon.consulting
\.gbiz$ whois-to-rdap.zerogon.consulting
\.george$ whois.nic.george
\.gl$ whois.nic.gl
\.hair$ whois.nic.hair
\.hr$ whois.dns.hr
\.imamat$ whois.nic.imamat
\.ir$ whois.nic.ir
\.lamborghini$ whois.nic.lamborghini
\.land$ whois-to-rdap.zerogon.consulting
\.lawyer$ whois-to-rdap.zerogon.consulting
\.lgbt$ whois-to-rdap.zerogon.consulting
\.lifestyle$ whois.registry.click
\.lpl$ whois.nic.lpl
\.marshalls$ whois-to-rdap.zerogon.consulting
\.merckmsd$ whois.nic.merckmsd
\.mr$ whois.nic.mr
\.mw$ whois.nic.mw
\.nra$ whois.nic.nra
\.organic$ whois-to-rdap.zerogon.consulting
\.pink$ whois-to-rdap.zerogon.consulting
\.place$ whois-to-rdap.zerogon.consulting
\.prime$ whois-to-rdap.zerogon.consulting
\.pwc$ whois.nic.pwc
\.sap$ whois.nic.sap
\.sener$ whois.nic.rwe
\.sew$ whois.nic.sew
\.skin$ whois.nic.skin
\.sn$ whois.nic.sn
\.software$ whois-to-rdap.zerogon.consulting
\.st$ whois.nic.st
\.taipei$ whois.nic.taipei
\.temasek$ whois.nic.temasek
\.travelers$ whois.nic.travelers
\.website$ whois.nic.website
\.xn--80asehdb$ whois.nic.xn--80asehdb
\.xn--czrs0t$ whois-to-rdap.zerogon.consulting
\.xn--fpcrj9c3d$ whois.nixiregistry.in
\.xn--h2breg3eve$ whois.nixiregistry.in
\.xn--mgbbh1a$ whois.nixiregistry.in
\.xn--qcka1pmc$ whois-to-rdap.zerogon.consulting
\.yachts$ whois.nic.yachts
\.yahoo$ whois.nic.yahoo
